### PR TITLE
Updates to match 12.6.0

### PR DESCRIPTION
**Pull request by dwradcliffe**
@dalehamel @pallan @kvs @baldowl

### CODE REVIEW

**Comment by pallan** [comment]
LGTM

**Comment by dalehamel** [comment]
I'm embarrassed to say that I actually don't understand what is going on
here.

Did you copy code from the chef-client proper?

**Comment by dwradcliffe** [comment]
Yes this is just copy/paste from chef proper. And removing our chef 11 hack.

**Comment by dwradcliffe** [comment]
And I included comments so it's easier to see what changed in the future.

**Comment by dalehamel** [comment]
@dwradcliffe ugh... I wish we could do a shadow based monkey patch instead of an override based monkey patch.

I suppose that's out of the question though :(

:+1:

**Comment by dwradcliffe** [comment]
I have an idea but I want to try it separately later.

**Pull request merged**
