### PR TITLE
patch data_bag() method

### PR DESCRIPTION
**Pull request by dwradcliffe**
@dalehamel @andrewjamesbrown @stonith @pallan @kvs

### CODE REVIEW

**Comment by dalehamel** [comment]
:+1:

**Comment by dalehamel** [comment]
We'll need a way to :tophat:, I guess that'll have to wait until the chef storm subsides.

**Comment by andrewjamesbrown** [comment]
LGTM

**Comment by dwradcliffe** [comment]
I'm going to do some tests before rolling out everywhere

**Comment by dwradcliffe** [comment]
Tested this inside chef-shell and it works, and it's MUCH faster.

**Pull request merged**
